Stoppable process.
dpfaffenbauer/ProcessManager pull request #39
Opened 2020-02-10 09:45 UTC by kubaplas

| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no

Added status and stoppable columns to processes table, also to all classes connected to Process model.
Status is displayed in the admin panel as an additional column. If the process is running and has stoppable flag set to true, button will show up in admin panel, which would change the status of the process to "stopping".
This way processes can detect if the user wants to stop given process and do so.

2020-02-10 09:48 UTC, dpfaffenbauer requested changes

2020-02-10 09:48 UTC, dpfaffenbauer commented on src/ProcessManagerBundle/Controller/ExecutableController.php
> +        $page = $request->get('page');
whats the point in that?

2020-02-10 09:48 UTC, dpfaffenbauer commented on src/ProcessManagerBundle/Resources/translations/admin.en.yml
> +processmanager_completed_with_exceptions: 'Competed (!)'
typo

2020-02-10 09:52 UTC, kubaplas commented on src/ProcessManagerBundle/Controller/ExecutableController.php
> +        $page = $request->get('page');
I removed the code.

2020-02-10 09:54 UTC, dpfaffenbauer commented
Good, the workflow is that PM only sets the status, the process it self needs to check if the status has been changed right?

2020-02-10 09:57 UTC, kubaplas commented
Exactly. I have PoC ready for Import Defitnions here: https://github.com/w-vision/DataDefinitions/pull/246nd=1

2020-03-23 07:43 UTC, dpfaffenbauer requested changes

2020-03-23 07:43 UTC, dpfaffenbauer commented on README.md
> +$process = $this->processRepository->findOneBy(['id' => $processId]);
`find($processId)`

2020-03-23 07:43 UTC, dpfaffenbauer commented
I think other than my comment, it seems fine

2020-03-23 09:03 UTC, kubaplas commented on README.md
> +$process = $this->processRepository->findOneBy(['id' => $processId]);
Changed.

2020-03-23 11:14 UTC, merged

2020-03-23 11:14 UTC, dpfaffenbauer commented
thanks a lot, again :)